PLATFORM = 6809
CC = m6809-unknown-gcc
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = m6809-unknown-ld
CFLAGS = -I../../Library/include -I../../Library/include/6809
COPT = -Os -fomit-frame-pointer
# Workaround for gcc6809 bug - register copy propagation issue
COPT += -fno-cprop-registers
LINKER_OPT = --oformat=raw -L../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc
LINKER_OPT += --script=../util/$(TARGET).link
ASM_OPT = -o
CRT0 = ../../Library/libs/crt0_6809.o

.SUFFIXES: .c .o

CSRCS = beep.c blockio.c display.c doscall.c editcor.c exec.c find.c
CSRCS += flexcall.c gemcall.c globals.c insert.c main.c misc.c modify.c
CSRCS += move.c rmxcall.c ucsd.c undo.c unixcall.c wildargs.c

OBJS = $(CSRCS:.c=.o)

levee: $(OBJS) $(CRT0)
	$(LINKER) -o levee $(LINKER_OPT) $^

$(OBJS): %.o: %.c
	$(CC) $(CFLAGS) $(COPT) -c $<

clean:
	rm -rf $(OBJS) *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *~ *.o *.asm levee levee.bin
