include $(FUZIX_ROOT)/Applications/rules.6809

SRCS  = dasm09.c

OBJS = $(SRCS:.c=.o)

APPS = dasm09

all: $(APPS)


dasm09: $(OBJS)
	$(LINKER) $(LINKER_OPT) -o dasm09 $(CRT0) dasm09.o


size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *~

rmbak:
	rm -f *~ core
