PLATFORM = 68000
CC = m68k-uclinux-gcc
ASM = m68k-uclinux-as
AR = m68k-uclinux-ar
LINKER = m68k-uclinux-ld
CFLAGS = -Os -fno-strict-aliasing -fomit-frame-pointer -fno-builtin -Wall -m68000 -I../../../Library/include -I../../../Library/include/68000
LINKER_OPT = -L../../../Library/libs -lc68000
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += --emit-relocs -L$(LIBGCCDIR) -lgcc -T ../../../Library/elf2flt.ld
CRT0 = ../../../Library/libs/crt0_68000.o
CRT0NS = ../../../Library/libs/crt0nostdio_68000.o
# For now while we get going. Really we want to use some kind of elf2zmagic
# with relocs.
ELF2FUZIX = elf2flt -s 16384
.SUFFIXES: .c .o

SRCS  = ac.c col.c dc.c diff.c ed.c makekey.c ptx.c sum.c wall.c
SRCS += accton.c  comm.c   dd.c      diffh.c  mesg.c     rev.c    test.c
SRCS += at.c      cron.c   deroff.c  join.c   newgrp.c   split.c  time.c
SRCS += atrun.c   crypt.c  diff3.c   look.c   pr.c       su.c     tsort.c
SRCS += pg.c	  tty.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): $(CRT0)

$(APPS) $(APPSNS): %: %.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT)
	$(ELF2FUZIX) -o $@ $@.bin


size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f *.o $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *.o

rmbak:
	rm -f *~ core

