PLATFORM = 6809
CC = m6809-unknown-gcc
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = m6809-unknown-ld
CFLAGS = -I../../../Library/include -I../../../Library/include/6809
LINKER_OPT = --oformat=raw -L../../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc
LINKER_OPT += --script=../../util/$(TARGET).link
ASM_OPT = -o
CRT0 = ../../../Library/libs/crt0_6809.o
CRT0NS = ../../../Library/libs/crt0nostdio_6809.o

.SUFFIXES: .c .o


SRCS  = ac.c      col.c    dc.c      diff.c   ptx.c      sum.c    wall.c
SRCS += accton.c  comm.c   dd.c      diffh.c  mesg.c     rev.c
SRCS += at.c      cron.c   deroff.c  join.c   newgrp.c   split.c
SRCS += atrun.c   crypt.c  diff3.c   look.c   pr.c       su.c     tsort.c
SRCS += pg.c      sort.c   tty.c

SRCSNS = ed.c makekey.c test.c time.c

SRCSTC = clear.c

OBJS = $(SRCS:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)
OBJSTC = $(SRCSTC:.c=.o)

APPSTC = $(OBJSTC:.o=)
APPSNS = $(OBJSNS:.o=)
APPS = $(OBJS:.o=)

APPS_ALL = $(APPS) $(APPSNS) $(APPSTC)

all: $(APPS_ALL) size.report

$(APPS) $(APPSTC): $(CRT0)
$(APPSNS): $(CRT0NS)
$(APPSTC): LINKER_OPT += -ltermcap6809

$(APPS_ALL): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $^

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f *.o $(APPS) $(APPSNS) $(APPSTC) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
