include $(FUZIX_ROOT)/Applications/rules.8080

SRCS  = ac.c col.c dc.c diff.c makekey.c ptx.c sum.c wall.c
SRCS += accton.c  comm.c   dd.c      diffh.c  mesg.c     rev.c    test.c
SRCS += at.c      cron.c   deroff.c  join.c   newgrp.c   split.c  time.c
SRCS += atrun.c   crypt.c  diff3.c   look.c   pr.c       su.c     tsort.c
SRCS += pg.c ed.c sort.c tty.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f *.o $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
