#
#	IntCode engine
#

include $(FUZIX_ROOT)/Applications/rules.6809

SRCS  = icint.c blib.c
OBJS = $(SRCS:.c=.o) blibv.o icintv.o

APPS = icint icintv run-time.i codegen.i b.i

all: $(APPS) sizes

$(OBJS): $(SRCS)

$(APPS): $(CRT0)

%: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $<

icintv.o: icint.c
	$(CC) $(CFLAGS) -c -DPAGEDMEM -o icintv.o icint.c

blibv.o: blib.c
	$(CC) $(CFLAGS) -c -DPAGEDMEM -o blibv.o blib.c

icint:  icint.o blib.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) icint.o  blib.o

icintv: icintv.o blibv.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) icintv.o blibv.o

sizes: $(APPS)
	ls -l $(APPS) > size.report

run-time.i: blib16.i
	cat blib16.i iclib.i > run-time.i

codegen.i:  cg.i run-time.i
	cat cg.i run-time.i > codegen.i

b.i:    syn.i trn.i run-time.i
	cat syn.i trn.i run-time.i > b.i

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.rel *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report
