#!/bin/sh

endian=
if [ "$1" = "-X" ]; then
        shift
        endian=-X
fi
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
        echo "Syntax: $0 [ -X ] filename isize bsize"
        echo ""
        echo "For a 1.44MB floppy disk, use isize=64, bsize=2880"
        echo "For a 32MB (or larger) hard disk, use isize=256, bsize=65535"
        exit 1
fi
if [ -z "$TARGET" ]; then
        echo "The TARGET was not set."
        exit 1
fi

VERSION=`cat ../../version.mk|grep \ VERSION| rev | cut -d ' ' -f 1 | rev`
sed -e "s/XXX/$VERSION/" <templates/issue >etc-files/issue
./build-filesystem-ng $endian -f $1 -g $2 $3 -p platform-$TARGET
