#undef CONFIG_SMP
#undef CONFIG_BUILD_PROTECTED
#define CONFIG_BOARD_LOOPSPERMSEC 11401U
#define CONFIG_BOOT_RUNFROMFLASH 1
#undef CONFIG_ARCH_GNU_NO_WEAKFUNCTIONS
#undef CONFIG_ARCH_HIPRI_INTERRUPT
#undef CONFIG_ARCH_MINIMAL_VECTORTABLE
#undef CONFIG_ARCH_NUSER_INTERRUPTS
#define CONFIG_ARCH_INTERRUPTSTACK 0
#undef CONFIG_IRQCHAIN
#undef CONFIG_IRQCOUNT
#undef CONFIG_SPINLOCK_IRQ
#undef CONFIG_ARCH_ARMV6M
#undef CONFIG_ARCH_ARMV8M
#undef CONFIG_ARMV8M_USEBASEPRI
#undef CONFIG_ARMV7M_USEBASEPRI
#undef CONFIG_ARMV7M_BASEPRI_WAR
#undef CONFIG_ARMV7M_LAZYFPU
#undef CONFIG_ARCH_FPU
#define CONFIG_ARCH_ARMV7M 1
#define CONFIG_ARCH_CHIP_TIVA 1
#define CONFIG_ARCH_CORTEXM4 1
#undef CONFIG_ARCH_CHIP_CC13X0
#undef CONFIG_ARCH_CHIP_CC13X2
#undef CONFIG_ARCH_CHIP_LM
#undef CONFIG_ARCH_CHIP_LM3S
#undef CONFIG_ARCH_CHIP_LM3S6918
#undef CONFIG_ARCH_CHIP_LM3S6432
#undef CONFIG_ARCH_CHIP_LM3S6965
#undef CONFIG_ARCH_CHIP_LM3S9B96
#undef CONFIG_ARCH_CHIP_LM3S9B92
#undef CONFIG_ARCH_CHIP_LM3S8962
#undef CONFIG_ARCH_CHIP_LM4F
#undef CONFIG_ARCH_CHIP_LM4F120
#define CONFIG_ARCH_CHIP_TM4C 1
#undef CONFIG_ARCH_CHIP_TM4C123
#undef CONFIG_ARCH_CHIP_TM4C123GH6PGE
#undef CONFIG_ARCH_CHIP_TM4C123GH6PZ
#undef CONFIG_ARCH_CHIP_TM4C123GH6ZRB
#undef CONFIG_ARCH_CHIP_TM4C123GH6PM
#undef CONFIG_ARCH_CHIP_TM4C123AH6PM
#define CONFIG_ARCH_CHIP_TM4C129 1
#define CONFIG_ARCH_CHIP_TM4C129XNCZAD 1
#undef CONFIG_ARCH_CHIP_TM4C1294NCPDT
#undef CONFIG_ARCH_CHIP_TM4C129ENCPDT
#define CONFIG_TIVA_GPIO_IRQS 1
#undef CONFIG_TIVA_GPIOA_IRQS
#undef CONFIG_TIVA_GPIOB_IRQS
#undef CONFIG_TIVA_GPIOC_IRQS
#undef CONFIG_TIVA_GPIOD_IRQS
#undef CONFIG_TIVA_GPIOE_IRQS
#undef CONFIG_TIVA_GPIOF_IRQS
#undef CONFIG_TIVA_GPIOG_IRQS
#undef CONFIG_TIVA_GPIOH_IRQS
#undef CONFIG_TIVA_GPIOJ_IRQS
#undef CONFIG_TIVA_GPIOK_IRQS
#undef CONFIG_TIVA_GPIOL_IRQS
#undef CONFIG_TIVA_GPIOM_IRQS
#undef CONFIG_TIVA_GPION_IRQS
#define CONFIG_TIVA_GPIOP_IRQS 1
#undef CONFIG_TIVA_GPIOQ_IRQS
#undef CONFIG_TIVA_GPIOR_IRQS
#undef CONFIG_TIVA_GPIOS_IRQS
#undef CONFIG_TIVA_GPIOT_IRQS
#define CONFIG_TIVA_I2C6 1
#undef CONFIG_TIVA_UART0_NONE
#define CONFIG_TIVA_UART0 1
#define CONFIG_TIVA_UART1_NONE 1
#undef CONFIG_TIVA_UART1
#define CONFIG_TIVA_UART2_NONE 1
#undef CONFIG_TIVA_UART2
#define CONFIG_TIVA_UART3_NONE 1
#undef CONFIG_TIVA_UAR3
#define CONFIG_TIVA_UART4_NONE 1
#undef CONFIG_TIVA_UART4
#define CONFIG_TIVA_UART5_NONE 1
#undef CONFIG_TIVA_UART5
#define CONFIG_TIVA_UART6_NONE 1
#undef CONFIG_TIVA_UART6
#define CONFIG_TIVA_UART7_NONE 1
#undef CONFIG_TIVA_UART6
#undef CONFIG_TIVA_EMAC_ENHANCEDDESC
/* #undef CONFIG_SYS_NNEST */
#undef CONFIG_LIB_SYSCALL

#undef CONFIG_DEBUG_GPIO_INFO
#define CONFIG_ARCH_LEDS 1
#define CONFIG_I2C 1
#define CONFIG_SENSORS 1
#define CONFIG_LM75_I2C 1
#define CONFIG_SENSORS_LM75 1
#define CONFIG_LM75_I2C_FREQUENCY 100000
#undef CONFIG_SUPPRESS_UART_CONFIG
#define CONFIG_UART0_SERIAL_CONSOLE 1
#undef CONFIG_UART1_SERIAL_CONSOLE
#undef CONFIG_UART2_SERIAL_CONSOLE
#undef CONFIG_UART3_SERIAL_CONSOLE
#undef CONFIG_UART4_SERIAL_CONSOLE
#undef CONFIG_UART5_SERIAL_CONSOLE
#undef CONFIG_UART6_SERIAL_CONSOLE
#undef CONFIG_UART7_SERIAL_CONSOLE
#define CONFIG_UART0_BAUD 115200
#define CONFIG_UART0_BITS 8
#define CONFIG_UART0_PARITY 0
#define CONFIG_UART0_2STOP 0
#define CONFIG_UART1_BAUD 115200
#define CONFIG_UART1_BITS 8
#define CONFIG_UART1_PARITY 0
#define CONFIG_UART1_2STOP 0
#undef CONFIG_UART2_BAUD
#undef CONFIG_UART2_BITS
#undef CONFIG_UART2_PARITY
#undef CONFIG_UART2_2STOP
#undef CONFIG_UART3_BAUD
#undef CONFIG_UART3_BITS
#undef CONFIG_UART3_PARITY
#undef CONFIG_UART3_2STOP
#undef CONFIG_UART4_BAUD
#undef CONFIG_UART4_BITS
#undef CONFIG_UART4_PARITY
#undef CONFIG_UART4_2STOP
#undef CONFIG_UART5_BAUD
#undef CONFIG_UART5_BITS
#undef CONFIG_UART5_PARITY
#undef CONFIG_UART5_2STOP
#undef CONFIG_UART6_BAUD
#undef CONFIG_UART6_BITS
#undef CONFIG_UART6_PARITY
#undef CONFIG_UART6_2STOP
#undef CONFIG_UART7_BAUD
#undef CONFIG_UART7_BITS
#undef CONFIG_UART7_PARITY
#undef CONFIG_UART7_2STOP

#define OK 0
