#

all:
	(cd util; make -f Makefile.$(CPU))
	(cd V7/cmd; make -f Makefile.$(CPU))
	(cd V7/cmd/sh; make -f Makefile.$(CPU))
	(cd V7/games; make -f Makefile.$(CPU))
	(cd cave; make -f Makefile.$(CPU))
	(cd cpm; make -f Makefile.$(CPU))
	(cd games; make -f Makefile.$(CPU))
	(cd ld09; make -f Makefile.$(CPU))
	(cd netd; make -f Makefile.$(CPU))
	(cd SmallC; make -f Makefile.$(CPU))
	(cd MWC/cmd; make -f Makefile.$(CPU))

clean:
	(cd util; make -f Makefile.$(CPU) clean)
	(cd V7/cmd; make -f Makefile.$(CPU) clean)
	(cd V7/cmd/sh; make -f Makefile.$(CPU) clean)
	(cd V7/games; make -f Makefile.$(CPU) clean)
	(cd cave; make -f Makefile.$(CPU) clean)
	(cd cpm; make -f Makefile.$(CPU) clean)
	(cd games; make -f Makefile.$(CPU) clean)
	(cd ld09; make -f Makefile.$(CPU) clean)
	(cd netd; make -f Makefile.$(CPU) clean)
	(cd SmallC; make -f Makefile.$(CPU) clean)
	(cd MWC/cmd; make -f Makefile.$(CPU) clean)

