PLATFORM = 6809
CC = m6809-unknown-gcc
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = m6809-unknown-ld
CFLAGS = -I../../Library/include -I../../Library/include/6809
# pointer to pointer gcc compilation problems: use -O0.
CCOPTS = -O0
LINKER_OPT = --oformat=raw -L../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc
LINKER_OPT += --script=../util/$(TARGET).link
ASM_OPT = -o
CRT0 = ../../Library/libs/crt0_6809.o


SRC = advent.c adventdb.c database.c english.c itverb.c lib.c saveadv.c \
      turn.c verb.c global.c


OBJ = $(SRC:.c=.o)

.SUFFIXES: .c .o

all: advent advent.db

advent.db: advgen
	./advgen -x > advent.db

advgen: advgen.c
	cc advgen.c -o ./advgen
	
.c.o:
	$(CC) $(CFLAGS) $(CCOPTS) -c $<

advent: $(OBJ) $(CRT0)
	$(LINKER) -o $@ $(LINKER_OPT) $^

clean:
	rm -f advent advent.db advgen *.rel *.asm *.lst core *.sym *.map *.noi *.lk *.ihx *.tmp *.bin *.o
