include $(FUZIX_ROOT)/Applications/rules.8080


SRC = advent.c adventdb.c database.c english.c itverb.c lib.c saveadv.c \
      turn.c verb.c


OBJ = $(SRC:.c=.o)

.SUFFIXES: .c .o

all: advent advent.db

advent.db: advgen
	./advgen > advent.db

advgen: advgen.c
	cc advgen.c -o ./advgen
	
.c.o:
	$(CC) $(CFLAGS) $(CCOPTS) -c $<

advent: $(OBJ)
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

clean:
	rm -f advent advent.db advgen *.rel *.asm *.lst core *.sym *.map *.noi *.lk *.ihx *.tmp *.bin *.o
