PLATFORM = 8080
CC = ack
ASM = ack
AR = aal
LINKER = ack
LIBPATH=../../Library/libs
LIBC=$(LIBPATH)/libc8080.a -lem.a
CFLAGS = -O2 -I../../Library/include -I../../Library/include/8080
ASM_OPT = -c -o
CRT0 = $(LIBPATH)/crt0_8080.o
CRT0NS = $(LIBPATH)/crt0nostdio_8080.o

.SUFFIXES: .c .o


SRC = advent.c adventdb.c database.c english.c itverb.c lib.c saveadv.c \
      turn.c verb.c


OBJ = $(SRC:.c=.o)

.SUFFIXES: .c .o

all: advent advent.db

advent.db: advgen
	./advgen -x > advent.db

advgen: advgen.c
	cc advgen.c -o ./advgen
	
.c.o:
	$(CC) $(CFLAGS) $(CCOPTS) -c $<

advent: $(OBJ)
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

clean:
	rm -f advent advent.db advgen *.rel *.asm *.lst core *.sym *.map *.noi *.lk *.ihx *.tmp *.bin *.o
