PLATFORM = 8080
CC = ack
ASM = ack
AR = aal
LINKER = ack
LIBPATH=../../../Library/libs
LIBC=$(LIBPATH)/libc8080.a -lem.a
CFLAGS = -O2 -I../../../Library/include -I../../../Library/include/8080
ASM_OPT = -c -o
CRT0 = $(LIBPATH)/crt0_8080.o
CRT0NS = $(LIBPATH)/crt0nostdio_8080.o

.SUFFIXES: .c .o


SRCS  = arithmetic.c  backgammon.c  fish.c  wump.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
