include $(FUZIX_ROOT)/Applications/rules.ns32k

SRCS  = arithmetic.c  backgammon.c  fish.c  wump.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): $(CRT0)

$(APPS) $(APPSNS): %: %.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)


size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core

