include $(FUZIX_ROOT)/Applications/rules.6303

SRCS  = arithmetic.c backgammon.c fish.c quiz.c wump.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) sizes

$(OBJS): %.o: %.c

%: %.o
	$(LINKER) -o $@ $(CRT0) $^  $(LINKER_LIB) 

sizes: $(APPS)
	ls -l $(APPS) >size.report

clean:
	rm -f $(OBJS)$(APPS) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *.o

rmbak:
	rm -f *~ core

