include $(FUZIX_ROOT)/Applications/rules.8080

SRCS  = args.c blok.c builtin.c cmd.c ctype.c error.c expand.c fault.c io.c \
        macro.c main.c msg.c name.c print.c service.c setbrk.c stak.c \
        string.c word.c xec.c glob.c

INCS  = brkincr.h ctype.h defs.h mac.h mode.h name.h stak.h sym.h timeout.h

OBJS = $(SRCS:.c=.o)
FOBJS = $(patsubst %.c,fshbuild/%.o, $(SRCS))

all: fsh sh

$(OBJS): $(INCS)

$(OBJS): %.o : %.c
	$(CC) -c $(CFLAGS) $(COPT) $<

$(FOBJS): fshbuild/%.o: %.c
	$(CC) -c $(CFLAGS) $(COPT) -DBUILD_FSH $< -o $@

sh: $(OBJS)
	$(LINKER) -o  $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

fsh: $(FOBJS)
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBPATH)/libreadline8080.a $(LIBC)

clean:
	rm -f $(OBJS) $(FOBJS) fsh sh $(SRCS:.c=) core *~

rmbak:
	rm -f *~ core
