CC = cl65
PLATFORM = --target fuzixtg
#PLATFORM = -tzx128

.SUFFIXES: .c .o

SRCS  = args.c blok.c builtin.c cmd.c ctype.c error.c expand.c fault.c io.c \
        macro.c main.c msg.c name.c print.c service.c setbrk.c stak.c \
        string.c word.c xec.c glob.c

INCS  = brkincr.h ctype.h defs.h mac.h mode.h name.h stak.h sym.h timeout.h

OBJS = $(SRCS:.c=.o)

LIBS = ../../../../Library/libs/c6502.lib

all: sh

sh: $(OBJS)
	$(CC) $(PLATFORM) ../../../../Library/libs/crt0_6502.o $(OBJS) $(LIBS) -o $@

$(OBJS): $(INCS)

.c.o:
	$(CC) -O2 $(PLATFORM) -D __STDC__ -c -I ../../../../Library/include/6502 -I ../../../../Library/include $<

clean: 
	rm -f $(OBJS) sh *~ core

rmbak:
	rm -f *~ core

