include $(FUZIX_ROOT)/Applications/rules.6303

.SUFFIXES: .c .o

SRCS  = args.c blok.c builtin.c cmd.c ctype.c error.c expand.c fault.c io.c \
        macro.c main.c msg.c name.c print.c service.c setbrk.c stak.c \
        string.c word.c xec.c glob.c

INCS  = brkincr.h ctype.h defs.h mac.h mode.h name.h stak.h sym.h timeout.h

OBJS = $(SRCS:.c=.o)
FOBJS = $(patsubst %.c,fshbuild_%.o, $(SRCS))

LIBS = ../../../../Library/libs/c6502.lib

all: sh fsh

sh: $(OBJS)
	$(LINKER) -o $@ $(CRT0) $^  $(LINKER_LIB) 

fsh: $(FOBJS)
	$(LINKER) -o $@ $(CRT0) $^ -lreadline6303 $(LINKER_LIB) 

$(OBJS): $(INCS)

$(FOBJS): $(INCS)

$(OBJS): %.o : %.c
	$(CC) -c $(CFLAGS) $(COPT) $<

$(FOBJS): fshbuild_%.o: %.c
	# -c and -o is busted if used together in cc65
	cp $< fshbuild_$<
	$(CC) -c $(CFLAGS) -c -DBUILD_FSH fshbuild_$<


clean: 
	rm -f $(OBJS) $(FOBJS) fsh sh *~ core

rmbak:
	rm -f *~ core

