PLATFORM = 6809
CC = m6809-unknown-gcc
# These are wrappers for lwasm and lwar
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = lwlink
CFLAGS =  -I../../../../Library/include -I../../../../Library/include/6502 -Wall -pedantic -fno-strict-aliasing
COPT = -Os
LINKER_OPT = --format=raw -L../../../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc -m sh.map
LINKER_OPT += --script=../../../util/$(TARGET).link
ASM_OPT = -o
CRT0 = ../../../../Library/libs/crt0_6809.o

.SUFFIXES: .c .o


SRCS  = args.c blok.c builtin.c cmd.c ctype.c error.c expand.c fault.c io.c \
        macro.c main.c msg.c name.c print.c service.c setbrk.c stak.c \
        string.c word.c xec.c glob.c

INCS  = brkincr.h ctype.h defs.h mac.h mode.h name.h stak.h sym.h timeout.h

OBJS = $(SRCS:.c=.o)

all: sh

$(OBJS): $(INCS)

$(OBJS): %.o : %.c
	$(CC) -c $(CFLAGS) $(COPT) $<

sh: $(OBJS)
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $(OBJS)

clean:
	rm -f $(OBJS) sh $(SRCS:.c=) core *~

rmbak:
	rm -f *~ core
