# Makefile.config for osh
#
# @(#)$Id: fa2fc2f3ff0023d3252a11f36a391e040ba93b97 $
#
# See INSTALL and Makefile for full details.
#

#
# Valentine's Day 2014 (Friday, 2014-02-14):
#
#	Twelve years ago today, Gunnar Ritter released osh as osh-020214.
#	Here's to 12 years of osh and UNIX love via osh-current and to
#	2014, the Year of Love <3
#

#
# The following specifies the osh date and version:
#
#	osh-current            == current master branch development
#	osh-YYYYMMDD-current   == current development snapshot
#	osh-YYYYMMDD-beta[1-9] == beta     release
#	osh-YYYYMMDD           == official release
#	osh-YYYYMMDD-p[1-9]    == patched  release
#
OSH_DATE=	January 15, 2015
OSH_VERSION=	osh-20150115
