extern unsigned errors;
extern void warning(const char *p);
extern void warningline(unsigned line, const char *p);
extern void error(const char *p);
extern void errorline(unsigned line, const char *p);
extern void fatal(const char *p);
extern void errorc(const unsigned c, const char *p);
extern void badtype(void);
extern void needlval(void);
extern void indirections(void);
extern void typemismatch(void);
extern void invalidtype(void);
extern void divzero(void);
extern void notconst(void);
