include $(FUZIX_ROOT)/Applications/rules.6303


SRCSNS = qrun.c fortune.c advint.c z1.c z2.c z3.c z4.c z5.c z8.c

SRCS  = adv01.c adv02.c adv03.c adv04.c adv05.c adv06.c adv07.c \
        adv08.c adv09.c adv10.c adv11.c adv12.c adv13.c adv14a.c adv14b.c \
        myst01.c myst02.c myst03.c myst04.c myst05.c myst06.c myst07.c \
        myst08.c myst09.c myst10.c myst11.c fortune-gen.c startrek.c \
	hamurabi.c cowsay.c

SRCSTC = sok.c

OBJS = $(SRCS:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)
OBJSTC = $(SRCSTC:.c=.o)

APPS = $(OBJS:.o=)
APPSNS = $(OBJSNS:.o=)
APPSTC = $(OBJSTC:.o=)

CFLAGS += -DCONFIG_IO_CUSS

all: $(APPS) $(APPSNS) $(APPSTC) fortune.dat sok.levels size.report

$(APPS): %: %.o
	$(LINKER) -o $@ $(CRT0) $^ $(LINKER_LIB)

$(APPSTC): %: %.o
	$(LINKER) -o $@ $(CRT0) $^ -ltermcap6303 $(LINKER_LIB)

$(APPSNS): %: %.o
	$(LINKER) -o $@ $(CRT0NS) $^ $(LINKER_LIB) 

fortune-gen-linux: fortune-gen.c
	$(CC) -o fortune-gen-linux $<

fortune.dat: fortune-gen-linux
	./fortune-gen-linux < fort.db >fortune.dat

sok.levels: sokmap
	./sokmap ljh.sok sok.levels >/dev/null

sokmap: sokmap.c sok.h
	$(CC) sokmap.c -o ./sokmap


size.report: $(APPS) $(APPSNS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(OBJSNS) $(APPS) $(APPSNS) $(APPTC) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
