include $(FUZIX_ROOT)/Applications/rules.6502

SRCSNS = qrun.c advint.c z1.c z2.c z3.c z4.c z5.c z8.c

SRCS  = adv01.c adv02.c adv03.c adv04.c adv05.c adv06.c adv07.c \
        adv08.c adv09.c adv10.c adv11.c adv12.c adv13.c adv14a.c adv14b.c \
        myst01.c myst02.c myst03.c myst04.c myst05.c myst06.c myst07.c \
        myst08.c myst09.c myst10.c myst11.c fortune-gen.c startrek.c \
	hamurabi.c cowsay.c taylormade.c

OBJS = $(SRCS:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)

APPS = $(OBJS:.o=)
APPSNS = $(OBJSNS:.o=)

CFLAGS += -DCONFIG_IO_CUSS

all: $(APPS) $(APPSNS) fortune sok size.report

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LINKER_TAIL)

$(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) $^ $(LINKER_TAIL)


#
#	Build the fortune data file
#
fortune-gen-linux: fortune-gen.c
	cc -o fortune-gen-linux $<

fortune.dat: fortune-gen-linux
	./fortune-gen-linux < fort.db >fortune.dat

fortune: fortune.dat fortune.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) fortune.o $(LINKER_TAIL)

sok.levels: sokmap
	./sokmap ljh.sok sok.levels >/dev/null

sokmap: sokmap.c sok.h
	cc sokmap.c -o ./sokmap

sok: sok.levels
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) sok.o $(LINKER_TAIL)



size.report: $(APPS) $(APPSNS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(OBJSNS) $(APPS) $(APPSNS) $(APPTC) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report
	rm -f fortune.dat fortune-gen-linux
	rm -f sokmap sok.levels

rmbak:
	rm -f *~ core
