include $(FUZIX_ROOT)/Applications/rules.8080

HOSTCC = gcc

SRCSNS = qrun.c fortune.c fweep.c

SRCS  = fortune-gen.c startrek.c hamurabi.c advint.c cowsay.c

#
#	ack currently seems to blow up with an apparently bogus error
#	on these
#
SRCSBUST = adv01.c adv02.c adv03.c adv04.c adv05.c adv06.c adv07.c \
        adv08.c adv09.c adv10.c adv11.c adv12.c adv13.c adv14a.c adv14b.c \
        myst01.c myst02.c myst03.c myst04.c myst05.c myst06.c myst07.c \
        myst08.c myst09.c myst10.c myst11.c 

OBJS = $(SRCS:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)

APPS = $(OBJS:.o=)
APPSNS = $(OBJSNS:.o=)

all: $(APPS) $(APPSNS) size.report

CFLAGS += -DCONFIG_IO_CUSS

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

$(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) $^ $(LIBC)

fortune-gen-linux: fortune-gen.c
	$(HOSTCC) -o $@ $<

fortune.dat: fortune-gen-linux
	./fortune-gen-linux < fort.db >fortune.dat

fortune: | fortune.dat

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(OBJSNS) $(APPS) $(APPSNS) *.lst *.map size.report
	rm -f fortune.dat fortune-gen-linux

