HOSTCC := $(CC)
PLATFORM = 68000
CC = m68k-uclinux-gcc
ASM = m68k-uclinux-as
AR = m68k-uclinux-ar
LINKER = m68k-uclinux-ld
CFLAGS = -fno-strict-aliasing -fomit-frame-pointer -fno-builtin -msoft-float -Wall -m68000 -Os -I../../Library/include -I../../Library/include/68000
LINKER_OPT = -L../../Library/libs -ltermcap68000 -lc68000
LINKER_FP_OPT = -L../../Library/libs -lm68000 -lc68000
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += --emit-relocs -L$(LIBGCCDIR) -lgcc -T ../../Library/elf2flt.ld
LINKER_FP_OPT += --emit-relocs -L$(LIBGCCDIR) -lgcc -T ../../Library/elf2flt.ld
CRT0 = ../../Library/libs/crt0_68000.o
CRT0NS = ../../Library/libs/crt0nostdio_68000.o
# For now while we get going. Really we want to use some kind of elf2zmagic
# with relocs.
ELF2FUZIX = elf2flt -s 16384
.SUFFIXES: .c .o

SRCSNS = 

SRCS  = adv01.c adv02.c adv03.c adv04.c adv05.c adv06.c adv07.c \
        adv08.c adv09.c adv10.c adv11.c adv12.c adv13.c adv14a.c adv14b.c \
        myst01.c myst02.c myst03.c myst04.c myst05.c myst06.c myst07.c \
	myst08.c myst09.c myst10.c myst11.c fortune-gen.c qrun.c fortune.c \
	z1.c z2.c z3.c z4.c z5.c z8.c startrek.c hamurabi.c cowsay.c advint.c

SRCSFP = 

OBJS = $(SRCS:.c=.o)
OBJSFP = $(SRCSFP:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)

APPS = $(OBJS:.o=)
APPSFP = $(OBJSFP:.o=)
APPSNS = $(OBJSNS:.o=)

CFLAGS += -DCONFIG_IO_CUSS

all: $(APPS) $(APPSNS) $(APPSFP) size.report

$(APPS): $(CRT0)
$(APPSFP): $(CRT0)
$(APPSNS): $(CRT0NS)

$(APPS) $(APPSNS): %: %.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT)
	$(ELF2FUZIX) -o $@ $@.bin

$(APPSFP): %: %.o
	$(LINKER) $^ -o $@.bin $(LINKER_FP_OPT)
	$(ELF2FUZIX) -o $@ $@.bin

fortune-gen-linux: fortune-gen.c
	$(HOSTCC) -o $@ $<

fortune.dat: fortune-gen-linux
	./fortune-gen-linux < fort.db >fortune.dat

fortune: | fortune.dat


size.report: $(APPS) $(APPSNS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(OBJSNS) $(APPS) $(APPSNS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
