PLATFORM = 6502
CC = cl65
ASM = ca65
LINKER = cl65
CFLAGS = -t none -O -D__STDC__ -c -O -I../../../../Library/include -I../../../../Library/include/6502 -DTARGET_Z80
LINKER_OPT = -L../../../../Library/libs -C ../../../../Library/libs/ld65-$(TARGET).cfg
ASM_OPT = -o
CRT0 = ../../../../Library/libs/crt0_6502.o

.SUFFIXES: .c .o

SRCS  = as0.c as1.c as2.c as3.c as4.c as6.c

INCS  = as.h obj.h

OBJS = $(SRCS:.c=.o)

all: as nm

$(OBJS): $(INCS)

$(OBJS): %.o : %.c
	$(CC) -c $(CFLAGS) $(COPT) $<

as: $(OBJS) $(CRT0)
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ c6502.lib -m $@.map

nm.c: obj.h

nm: nm.o $(CRT0)
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ c6502.lib -m $@.map

clean:
	rm -f $(OBJS) as $(SRCS:.c=) core *~ *.o

rmbak:
	rm -f *~ core
