include $(FUZIX_ROOT)/Applications/rules.6809

SRCS  = as0.c as1.c as2.c as3.c as4.c as6.c

INCS  = as.h obj.h

OBJS = $(SRCS:.c=.o)

# Until we have a 6809 target finished
CFLAGS += -DTARGET_Z80

all: as nm

$(OBJS): $(INCS)

$(OBJS): %.o : %.c
	$(CC) -c $(CFLAGS) $(COPT) $<

as: $(OBJS) $(CRT0)
	$(LINKER) -o $@ $(LINKER_OPT) $^

nm.c: obj.h

nm: nm.o $(CRT0)
	$(LINKER) -o $@ $(LINKER_OPT) $^

clean:
	rm -f $(OBJS) as $(SRCS:.c=) core *~ *.o

rmbak:
	rm -f *~ core
