include $(FUZIX_ROOT)/Applications/rules.68hc11

# Until we add HC11 support
CFLAGS += -DTARGET_Z80

SRCS  = as0.c as1.c as2.c as3.c as4.c as6.c

INCS  = as.h obj.h

OBJS = $(SRCS:.c=.o)

all: as nm

$(OBJS): $(INCS)

$(OBJS): %.o : %.c
	$(CC) -c $(CFLAGS) $(COPT) $<

as: $(OBJS)
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LINKER_TAIL)

nm.c: obj.h

nm: nm.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LINKER_TAIL)

clean:
	rm -f $(OBJS) as $(SRCS:.c=) core *~ *.o

rmbak:
	rm -f *~ core
