include $(FUZIX_ROOT)/Applications/rules.$(USERCPU)

SRCS  = dw.c dwgetty.c dwterm.c dwdate.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): $(CRT0)

$(APPS) $(APPSNS): %: %.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *.o

rmbak:
	rm -f *~ core
