include $(FUZIX_ROOT)/Applications/rules.$(USERCPU)

SRCS  = dw.c dwgetty.c dwterm.c dwdate.c

OBJS = $(SRCS:.c=.o)
APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(OBJS): %.o : %.c
	$(CC) -c $(CFLAGS) $(COPT) $<

$(APPS): %: %.o
	$(LINKER) $(CRT0) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *.o

rmbak:
	rm -f *~ core

