include $(FUZIX_ROOT)/Applications/rules.68000

SRCS  = netd.c uip.c uiplib.c timer.c clock-arch.c uip_arp.c telnet.c lwwire.c
SRCS += echoping.c dig.c gethostbyname.c httpd.c coconic.c ping.c ntpdate.c
SRCS += htget.c tinyirc.c linein.c ifconfig.c slip.c

OBJS = $(SRCS:.c=.o)

APPS = netd-slip telnet echoping dig httpd ping ntpdate htget tinyirc ifconfig

CFLAGS += -DNETD_BIG_ENDIAN

all: $(APPS)

netd-slip: $(CRT0) netd.o uip.o uiplib.o timer.o clock-arch.o uip_arp.o slip.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

telnet: $(CRT0) telnet.o gethostbyname.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

echoping: $(CRT0) echoping.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

dig: $(CRT0) dig.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

httpd: $(CRT0) httpd.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

ping: $(CRT0) ping.o gethostbyname.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

ntpdate: $(CRT0) ntpdate.o gethostbyname.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

htget:	$(CRT0) htget.o gethostbyname.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

tinyirc: $(CRT0) tinyirc.o linein.o gethostbyname.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

ifconfig: $(CRT0) ifconfig.o linein.o gethostbyname.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin


size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *~

rmbak:
	rm -f *~ core
