include $(FUZIX_ROOT)/Target/rules.6809

CFLAGS += -DNETD_BIG_ENDIAN

SRCS  = netd.c uip.c uiplib.c timer.c clock-arch.c uip_arp.c telnet.c lwwire.c
SRCS += echoping.c dig.c gethostbyname.c httpd.c coconic.c ping.c ntpdate.c
SRCS += htget.c tinyirc.c linein.c ifconfig.c

OBJS = $(SRCS:.c=.o)

APPS = netd-lwwire netd-coconic telnet echoping dig httpd ping ntpdate htget
APPS += tinyirc ifconfig

.PHONY: all
all: $(APPS)

netd-lwwire: $(CRT0) netd.o uip.o uiplib.o timer.o clock-arch.o uip_arp.o lwwire.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

netd-coconic: $(CRT0) netd.o uip.o uiplib.o timer.o clock-arch.o uip_arp.o coconic.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

telnet: $(CRT0) telnet.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

echoping: $(CRT0) echoping.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

dig: $(CRT0) dig.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

httpd: $(CRT0) httpd.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

ping: $(CRT0) ping.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

ntpdate: $(CRT0) ntpdate.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

htget: $(CRT0) htget.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

tinyirc: $(CRT0) tinyirc.o linein.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

ifconfig: $(CRT0) ifconfig.o
	$(LINKER) $(LINKER_OPT) -o $@ $^ $(LINKER_TAIL)

size.report: $(APPS)
	ls -l $^ > $@

.PHONY: clean
clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *~

.PHONY: rmbak
rmbak:
	rm -f *~ core
