include $(FUZIX_ROOT)/Target/rules.6809

CFLAGS += -DNETD_BIG_ENDIAN

SRCS  = netd.c uip.c uiplib.c timer.c clock-arch.c uip_arp.c telnet.c lwwire.c
SRCS += echoping.c dig.c gethostbyname.c httpd.c coconic.c ping.c ntpdate.c
SRCS += htget.c tinyirc.c linein.c ifconfig.c

OBJS = $(SRCS:.c=.o)

APPS = netd

all: $(APPS)


netd: $(OBJS)
	$(LINKER) $(LINKER_TAIL) -o netd-lwwire $(CRT0) netd.o uip.o uiplib.o timer.o clock-arch.o uip_arp.o lwwire.o
	$(LINKER) $(LINKER_TAIL) -o netd-coconic $(CRT0) netd.o uip.o uiplib.o timer.o clock-arch.o uip_arp.o coconic.o
	$(LINKER) $(LINKER_TAIL) -o telnet $(CRT0) telnet.o gethostbyname.o
	$(LINKER) $(LINKER_TAIL) -o echoping $(CRT0) echoping.o
	$(LINKER) $(LINKER_TAIL) -o dig $(CRT0) dig.o
	$(LINKER) $(LINKER_TAIL) -o httpd $(CRT0) httpd.o
	$(LINKER) $(LINKER_TAIL) -o ifconfig $(CRT0) ifconfig.o
	$(LINKER) $(LINKER_TAIL) -o ping $(CRT0) ping.o gethostbyname.o
	$(LINKER) $(LINKER_TAIL) -o ntpdate $(CRT0) ntpdate.o gethostbyname.o
	$(LINKER) $(LINKER_TAIL) -o htget $(CRT0) htget.o gethostbyname.o
	$(LINKER) $(LINKER_TAIL) -o tinyirc $(CRT0) tinyirc.o linein.o gethostbyname.o

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *~

rmbak:
	rm -f *~ core
