PLATFORM = 6809
CC = m6809-unknown-gcc
# These are wrappers for lwasm and lwar
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = lwlink
CFLAGS = -I../../Library/include -I../../Library/include/6809
CFLAGS += -O0 -msoft-reg-count=0 -mfar-stack-param -fomit-frame-pointer
LINKER_OPT = --format=raw -L../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc
LINKER_OPT += --script=../util/$(TARGET).link
ASM_OPT = -o
CRT0 = ../../Library/libs/crt0_6809.o

.SUFFIXES: .c .o

CFLAGS += -DNETD_BIG_ENDIAN

SRCS  = netd.c uip.c uiplib.c timer.c clock-arch.c uip_arp.c telnet.c lwwire.c
SRCS += echoping.c dig.c gethostbyname.c httpd.c coconic.c ping.c ntpdate.c
SRCS += htget.c tinyirc.c linein.c

OBJS = $(SRCS:.c=.o)

APPS = netd

all: $(APPS)


netd: $(OBJS)
	$(LINKER) $(LINKER_OPT) -o netd-lwwire $(CRT0) netd.o uip.o uiplib.o timer.o clock-arch.o uip_arp.o lwwire.o
	$(LINKER) $(LINKER_OPT) -o netd-coconic $(CRT0) netd.o uip.o uiplib.o timer.o clock-arch.o uip_arp.o coconic.o
	$(LINKER) $(LINKER_OPT) -o telnet $(CRT0) telnet.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o echoping $(CRT0) echoping.o
	$(LINKER) $(LINKER_OPT) -o dig $(CRT0) dig.o
	$(LINKER) $(LINKER_OPT) -o httpd $(CRT0) httpd.o
	$(LINKER) $(LINKER_OPT) -o ping $(CRT0) ping.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o ntpdate $(CRT0) ntpdate.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o htget $(CRT0) htget.o gethostbyname.o
	$(LINKER) $(LINKER_OPT) -o tinyirc $(CRT0) tinyirc.o linein.o gethostbyname.o

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *~

rmbak:
	rm -f *~ core
