include $(FUZIX_ROOT)/Applications/rules.68000

APPS = flashrom

SRCS  = flashrom.c

OBJS = $(SRCS:.c=.o)

all: $(APPS) size.report

flashrom: $(CRT0) flashrom.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

size.report: $(APPS)
	ls -l $< > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) *.lst *.map size.report

