include $(FUZIX_ROOT)/Applications/rules.ns32k

APPS = flashrom

SRCS  = flashrom.c

OBJS = $(SRCS:.c=.o)

all: $(APPS) size.report

flashrom: $(CRT0) flashrom.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

size.report: $(APPS)
	ls -l $< > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) *.lst *.map size.report

