PLATFORM = 8080
CC = ack
ASM = ack
AR = aal
LINKER = ack
LIBPATH=../../Library/libs
LIBC=$(LIBPATH)/libc8080.a -lem.a
CFLAGS = -I../../Library/include -I../../Library/include/8080
ASM_OPT = -c -o
CRT0 = $(LIBPATH)/crt0_8080.o
CRT0NS = $(LIBPATH)/crt0nostdio_8080.o

.SUFFIXES: .c .o

APPS = flashrom

SRCS  = flashrom.c

OBJS = $(SRCS:.c=.o)

all: $(APPS) size.report

flashrom: flashrom.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $< $(LIBC)

size.report: $(APPS)
	ls -l $< > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) *.lst *.map size.report

