extern void others(void);
extern char *chcopy(char *p, char *q);
extern char *writem(int *pp);
extern char *symnam(int i);
extern void summary(void);
extern void error(char *s, ...);
extern void aryfil(int *v, int n, int c);
extern int setunion(int *a, int *b);
extern void prlook(struct looksets *p);
extern void cpres(void);
extern void cpfir(void);
extern int state(int c);
extern void putitem(int *ptr, struct looksets *lptr);
extern void cempty(void);
extern void stagen(void);
extern void closure(int i);
extern struct looksets *flset(struct looksets *p);
extern void setup(int argc, char *argv[]);
extern void finact(void);
extern int defin(int t, char *s);
extern void defout(void);
extern char *cstash(char *s);
extern int gettok(void);
extern int fdtype(int t);
extern int chfind(int t, char *s);
extern void cpyunion(void);
extern void cpycode(void);
extern int skipcom(void);
extern void cpyact(int offset);
extern void output(void);
extern int apack(int *p, int n);
extern void go2out(void);
extern void go2gen(int c);
extern void precftn(int r, int t, int s);
extern void wract(int i);
extern void wrstate(int i);
extern void wdef(char *s, int n);
extern void warray(char *s, int *v, int n);
extern void hideprod(void);
extern void callopt(void);
extern void gin(int i);
extern void stin(int i);
extern int nxti(void);
extern void osummary(void);
extern void aoutput(void);
extern void arout(char *s, int *v, int n);
extern int gtnm(void);
