include $(FUZIX_ROOT)/Applications/rules.8080

.SUFFIXES: .c .o

SRCS = io_base.c keyboard_base.c plato.c protocol.c screen_base.c terminal.c \
       touch_base.c tgi_ascii.c

FSRCS = fuzix/font.c fuzix/io.c fuzix/keyboard.c fuzix/scale.c fuzix/screen.c \
	fuzix/splash.c fuzix/terminal_char_load.c fuzix/touch.c

INC = io.h keyboard.h plato_key.h protocol.h screen.h terminal.h touch.h

all:    plato

OBJS = $(SRCS:.c=.o)
FOBJS = $(patsubst fuzix/%.c,%.o, $(FSRCS))

plato: $(OBJS) $(FOBJS)
	$(LINKER) $(LINKER_OPT) -o plato $(CRT0) $(OBJS) $(FOBJS) $(LIBC)

$(OBJS): %.o: %.c
	$(CC) $(COPT) $(CFLAGS) -c $< -o $@

$(FOBJS): %.o: fuzix/%.c
	$(CC) $(COPT) $(CFLAGS) -c $< -o $@

$(OBJS) : $(INC)

$(FOBJS) : $(INC)

clean:
	rm -f *.o *.rel *.lst *.sym *.asm *.map *.noi *.lk *.bin *~ plato
	(cd fuzix; rm -f *.o *.rel *.lst *.sym *.asm *.map *.noi *.lk *.bin *~ )
