PLATFORM = 6809
CC = m6809-unknown-gcc
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = m6809-unknown-ld
CFLAGS =  -I../../Library/include -I../../Library/include/6809 -Wall -pedantic -fno-strict-aliasing
COPT = -Os
LINKER_OPT = --oformat=raw -L../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
CRT0 = ../../Library/libs/crt0_6809.o
LINKER_OPT += -L$(LIBGCCDIR) -lgcc -Map=ld09.map 
LINKER_OPT += --script=../util/$(TARGET).link $(CRT0)
ASM_OPT = -o

.SUFFIXES: .c .o

SRCS = io_base.c keyboard_base.c plato.c protocol.c screen_base.c terminal.c \
       touch_base.c tgi_ascii.c

FSRCS = fuzix/font.c fuzix/io.c fuzix/keyboard.c fuzix/scale.c fuzix/screen.c \
	fuzix/splash.c fuzix/terminal_char_load.c fuzix/touch.c

INC = io.h keyboard.h plato_key.h protocol.h screen.h terminal.h touch.h

all:    plato

OBJS = $(SRCS:.c=.o)
FOBJS = $(patsubst fuzix/%.c,%.o, $(FSRCS))

plato: $(OBJS) $(FOBJS)
	$(LINKER) $(LINKER_OPT) -o plato $(OBJS) $(FOBJS)

$(OBJS): %.o: %.c
	$(CC) $(COPT) $(CFLAGS) -c $< -o $@

$(FOBJS): %.o: fuzix/%.c
	$(CC) $(COPT) $(CFLAGS) -c $< -o $@

$(OBJS) : $(INC)

$(FOBJS) : $(INC)

clean:
	rm -f *.o *.rel *.lst *.sym *.asm *.map *.noi *.lk *.bin *~ plato
	(cd fuzix; rm -f *.o *.rel *.lst *.sym *.asm *.map *.noi *.lk *.bin *~ )
