include $(FUZIX_ROOT)/Applications/rules.6303

SRCS = io_base.c keyboard_base.c plato.c protocol.c screen_base.c terminal.c \
       touch_base.c tgi_ascii.c

FSRCS = fuzix/font.c fuzix/io.c fuzix/keyboard.c fuzix/scale.c fuzix/screen.c \
	fuzix/splash.c fuzix/terminal_char_load.c fuzix/touch.c

INC = io.h keyboard.h plato_key.h protocol.h screen.h terminal.h touch.h

# cc65 is weird. Tell it to cc foo/bar.c -o bar.o and it puts bar.o with the
# source code!
OBJS = $(SRCS:.c=.o)
FOBJS = $(FSRCS:.c=.o)

all:    plato

plato: $(OBJS) $(FOBJS)
	$(LINKER) -o $@ $(CRT0) $^  $(LINKER_LIB) 

$(OBJS): %.o: %.c
	$(CC) $(COPT) $(CFLAGS) -c $< -o $@

$(FOBJS): %.o: %.c
	$(CC) $(COPT) $(CFLAGS) -c $< -o $@

$(OBJS) : $(INC)

$(FOBJS) : $(INC)

clean:
	rm -f *.o *.rel *.lst *.sym *.asm *.map *.noi *.lk *.bin *~ plato
	(cd fuzix; rm -f *.o *.rel *.lst *.sym *.asm *.map *.noi *.lk *.bin *~ )
