ROOT = ../..
include $(ROOT)/Target/rules.armm0
LINKER_OPT += -lcurses$(PLATFORM) -ltermcap$(PLATFORM) -lc$(PLATFORM)

SRCS  = invaders.c
OBJS = $(SRCS:.c=.o)
APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): $(CRT0)

$(APPS) : %: %.o
	$(LINKER) $^ -o $@.debug $(LINKER_OPT)
	$(STRIP) $(STRIP_OPT) -o $@ $@.debug

size.report: $(APPS) $(APPSNS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) *.o core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
