include $(FUZIX_ROOT)/Applications/rules.68hc11

SRCS  = invaders.c
OBJS = $(SRCS:.c=.o)
APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS) $(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ -lcurses68hc11 -ltermcap68hc11 $(LINKER_TAIL)

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) *.o core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
