PLATFORM = 8080
CC = ack
ASM = ack
AR = aal
LINKER = ack
LIBPATH=../../Library/libs
LIBC=$(LIBPATH)/libc8080.a -lem.a
CFLAGS = -O2 -I../../Library/include -I../../Library/include/8080
include $(FUZIX_ROOT)/Applications/rules.8080

SRCS  = invaders.c
OBJS = $(SRCS:.c=.o)
APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS) $(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBPATH)/libcurses8080.a $(LIBPATH)/libtermcap8080.a $(LIBC)

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) *.o core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
