include $(FUZIX_ROOT)/Applications/rules.riscv32

SRCS  = invaders.c
OBJS = $(SRCS:.c=.o)
APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): $(CRT0)

$(APPS) : %: %.o
	$(LINKER) $^ -o $@ $(LINKER_OPT) -lcursesriscv32 -ltermcapriscv32 $(LINKER_TAIL)

size.report: $(APPS) $(APPSNS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) *.o core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
