include $(FUZIX_ROOT)/Applications/rules.8085

SRCS  = invaders.c

OBJS = $(SRCS:.c=.o)
APPS = $(OBJS:.o=)
all: $(APPS) size.report

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ -lcurses8085 -ltermcap8085 $(LINKER_LIB)

size.report: $(APPS) $(APPSNS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) *.o core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
