include $(FUZIX_ROOT)/Applications/rules.68000

SRCS  = invaders.c
OBJS = $(SRCS:.c=.o)
APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): $(CRT0)

$(APPS) : %: %.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) -lcurses68000 -ltermcap68000 $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

size.report: $(APPS) $(APPSNS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) *.o core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
