include $(FUZIX_ROOT)/Target/rules.$(USERCPU)

SRCS  = invaders.c
OBJS = $(SRCS:.c=.o)
APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS) : %: %.o
	$(LINKER) $(CRT0) $^ -o $@ $(LINKER_OPT) -lcurses$(USERCPU) -ltermcap$(USERCPU) $(LINKER_TAIL)

size.report: $(APPS) $(APPSNS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) *.o core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
