/* PILOT code source file - generated by RPilot 1.4 */

#include "foo.h"

extern void run_bound( char *code[] );

void run_pilot(void)
{
char *pilot_data[] = {
": Welcome to interactive RPilot!",
": ",
": Simply enter your commands, or `quit\' to exit.",
": $command",
": quit",
": done",
": $command",
": input",
NULL
};

run_bound( pilot_data );
}

int main( int argc, char *argv[] )
{
  run_pilot();
  return 0;
}

