include $(FUZIX_ROOT)/Applications/rules.68000

APPS = ue.fuzix ue.ansi ue

SRCS  = ue.c term-fuzix.c term-ansi.c term.c

OBJS = $(SRCS:.c=.o)

all: $(APPS) size.report

ue.fuzix: $(CRT0NS) ue.o term-fuzix.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

ue.ansi: $(CRT0NS) ue.o term-ansi.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

ue: $(CRT0) ue.o term.o
	$(LINKER) $^ -o $@.bin -ltermcap68000 $(LINKER_OPT) $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

size.report: $(APPS)
	ls -l $< > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) *.lst *.map size.report *.o *.rel
