include $(FUZIX_ROOT)/Applications/rules.6502

OBJS = ue.o
LIBS = term-ansi.c term-fuzix.c term.c

all: ue.fuzix ue.ansi ue

$(OBJS): ue.h
$(LIBS): ue.h

.c.o:
	$(CC) $(COPT) $(CFLAGS) $(DEFS) -c $< -o $@

ue.fuzix: $(OBJS) term-fuzix.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) $^ $(LINKER_TAIL)

ue.ansi: $(OBJS) term-ansi.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) $^ $(LINKER_TAIL)

ue: $(OBJS) term.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ termcap6502.lib $(LINKER_TAIL)

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) *.lst *.map size.report *.o *.rel
