include $(FUZIX_ROOT)/Applications/rules.6809

APPS = ue.fuzix ue.ansi ue

SRCS  = ue.c term-fuzix.c term-ansi.c term.c

OBJS = $(SRCS:.c=.o)

all: $(APPS) size.report

$(APPS): ue.h

ue.fuzix: ue.o term-fuzix.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) ue.o term-fuzix.o

ue.ansi: ue.o term-ansi.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) ue.o term-ansi.o

ue: ue.o term.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) ue.o term.o -ltermcap6809

size.report: $(APPS)
	ls -l $< > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) *.lst *.map size.report *.o *.rel

