include $(FUZIX_ROOT)/Applications/rules.6809

SRCS  = ac.c almanac.c at.c calendar.c col.c cron.c deroff.c du.c ed.c \
	expr.c find.c m4.c make.c moo.c pr.c sort.c tar.c test.c ttt.c units.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): $(CRT0)

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $^

expr.c: expr.y

find.c: find.y

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
