PLATFORM = 6502
CC = cl65
ASM = ca65
LINKER = cl65
CFLAGS = -t none -O -D__STDC__ -c -O -I../../../Library/include -I../../../Library/include/6502
LINKER_OPT = -L../../../Library/libs -C ../../../Library/libs/ld65-$(TARGET).cfg
ASM_OPT = -o
CRT0 = ../../../Library/libs/crt0_6502.o
CRT0NS = ../../../Library/libs/crt0nostdio_6502.o

.SUFFIXES: .c .o .y

SRC  = ac.c almanac.c at.c col.c cron.c deroff.c ed.c find.c make.c \
	moo.c pr.c tar.c ttt.c calendar.c m4.c
# no FP so no units
SRCNS = expr.c test.c

OBJ = $(SRC:.c=.o)
OBJNS = $(SRCNS:.c=.o)

APPS = $(OBJ:.o=) 
APPSNS = $(OBJNS:.o=) 

all: $(APPS) $(APPSNS) sizes

expr.c: expr.y

find.c: find.y

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ c6502.lib -m $@.map

$(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) $^ c6502.lib -m $@.map

sizes: $(APPS)
	ls -l $(APPS) >size.report

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ size.report *.o

rmbak:
	rm -f *~ core

