include $(FUZIX_ROOT)/Applications/rules.68000

SRCS  = ac.c almanac.c at.c calendar.c col.c cron.c deroff.c du.c ed.c expr.c
SRCS += find.c m4.c make.c moo.c pr.c tar.c test.c ttt.c units.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): %: %.o
	$(LINKER) $(LINKER_OPT) $(CRT0) $^ -o $@.bin $(LINKER_TAIL)
	$(ELF2FUZIX) -o $@ $@.bin

expr.c: expr.y

find.c: find.y

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *.o

rmbak:
	rm -f *~ core

