include $(FUZIX_ROOT)/Applications/rules.6502

SRC  = ac.c almanac.c at.c col.c cron.c deroff.c ed.c find.c make.c \
	moo.c pr.c tar.c ttt.c calendar.c m4.c
# no FP so no units
SRCNS = expr.c test.c

OBJ = $(SRC:.c=.o)
OBJNS = $(SRCNS:.c=.o)

APPS = $(OBJ:.o=) 
APPSNS = $(OBJNS:.o=) 

all: $(APPS) $(APPSNS) sizes

expr.c: expr.y

find.c: find.y

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LINKER_TAIL)

$(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) $^ $(LINKER_TAIL)

sizes: $(APPS)
	ls -l $(APPS) >size.report

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ size.report *.o

rmbak:
	rm -f *~ core

