include $(FUZIX_ROOT)/Target/rules.$(USERCPU)

SRC = append.c ar.c archive.c contents.c delete.c extract.c misc.c \
	move.c print.c replace.c strmode.c

.SUFFIXES: .c .o

OBJ = $(SRC:.c=.o)

all: ar

.c.o:
	$(CC) $(CFLAGS) $(CCOPTS) -c $<

ar: $(OBJ)
	$(LINKER) $(CRT0) $^ -o $@ $(LINKER_OPT) $(LINKER_TAIL)

clean:
	rm -f *.o ar core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
