#define PANIC_DOUBLE_FREE	"double free"
#define PANIC_MAXSWAP		"maxswap"
#define PANIC_NOTSELF		"notself"
#define PANIC_NOTTY		"no tty"
#define PANIC_NOFILESYS		"no filesys"
#define PANIC_NOROOT		"no root"
#define PANIC_MAPOVER		"map over"
#define PANIC_ALREADYSWAP	"already swapped"
#define PANIC_FREE0		"free0"
#define PANIC_WANTBSYB		"want busy block"
#define PANIC_NOFREEB		"no free buffers"
#define PANIC_BDR_INVD		"bdread: invalid dev"
#define PANIC_BDW_INVD		"bdwrite: invalid dev"
#define PANIC_CDR_INVD		"cdread: invalid dev"
#define PANIC_CDW_INVD		"cdwrite: invalid dev"
#define PANIC_DCL_INVD		"d_close: bad device"
#define PANIC_MLEAK		"mem_alloc: leak"
#define PANIC_IOPEN_BAD		"i_open: bad dev"
#define PANIC_GD_BAD		"getdev bad dev"
#define PANIC_IFREE_BADI	"i_free: bad ino"
#define PANIC_INODE_FREED	"inode freed."
#define PANIC_VALIDBLK_NM	"validblk: not mounted"
#define PANIC_VALIDBLK_INV	"validblk: invalid blk"
#define PANIC_GETINO_BADT	"getinode: bad desc table"
#define PANIC_GETINO_OFT	"getinode: bad OFT"
#define PANIC_FMOUNT_NOPEN	"fmount: can't open filesystem"
#define PANIC_CORRUPTI		"corrupt inode"
#define PANIC_VOODOO		"psleep: voodoo"
#define PANIC_GETPROC		"getproc: extra running"
#define PANIC_EI		"getproc: can't ei"
#define PANIC_KILLED_INIT	"killed init"
#define PANIC_DOEXIT		"doexit won't exit"
#define PANIC_NOINIT		"no /init"
#define PANIC_BADFREE		"bad free"
