export CROSS_AS=as9995
export CROSS_LD=ld9995
export CROSS_CC=cc9995
export CROSS_CCOPTS=-c -X -I$(ROOT_DIR)/cpu-tms9995 -I$(ROOT_DIR)/platform/platform-$(TARGET) -I$(ROOT_DIR)/include
export CROSS_CC_SEG1=
export CROSS_CC_SEG2=
export CROSS_CC_SEG3=
export CROSS_CC_SEGDISC=
export CROSS_CC_VIDEO=
export CROSS_CC_FONT=
export CROSS_CC_NETWORK=
export CROSS_CC_SYS1=
export CROSS_CC_SYS2=
export CROSS_CC_SYS3=
export CROSS_CC_SYS4=
export CROSS_CC_SYS5=
export ASOPTS=
export ASMEXT = .s
export BINEXT = .o
export BITS=16
export EXECFORMAT=16
