#!/bin/sh

if [ -e /opt/ccz80/bin/ccz80 ]; then
	echo "ccz80: installed"
	exit 0
fi

cd Applications/assembler
make -f Cross.z80
make -f Cross.z80 install

echo "Now install the Fuzix Compiler Kit"
echo "https://github.com/EtchedPixels/Fuzix-Compiler-Kit.git"
