#ifndef FUNCS_H
#define FUNCS_H

extern void edit();
extern void next_file();
extern void prev_file();
extern void quit();
extern void init_option();
extern void toggle_option();
extern void scan_option();
extern void forward();
extern void backward();
extern void repaint();
extern void jump_forw();
extern void jump_back();
extern void jump_percent();
extern void jump_loc();
extern void init_mark();
extern void setmark();
extern void gomark();
extern void search();
extern int ch_seek();
extern int ch_end_seek();
extern POSITION ch_length();
extern POSITION ch_tell();
extern int ch_forw_get();
extern int ch_back_get();
extern void ch_init();
extern POSITION position();
extern void add_forw_pos();
extern void add_back_pos();
extern void pos_clear();
extern int onscreen();
extern POSITION forw_line();
extern POSITION back_line();
extern void put_line();
extern int control_char();
extern int carat_char();
extern void flush();
extern void dropout();
extern void cputc();
extern void cputs();
extern void error();
extern int error_width();
extern void raw_mode();
extern void get_term();
extern void init();
extern void deinit();
extern void home();
extern void add_line();
extern void lower_left();
extern void bell();
extern void vbell();
extern void clear();
extern void clear_eol();
extern void so_enter();
extern void so_exit();
extern void ul_enter();
extern void ul_exit();
extern void backspace();
extern void putbs();
extern char * eq_message();
extern char * pr_string();
extern void prewind();
extern int pappend();
extern POSITION forw_raw_line();
extern POSITION back_raw_line();
extern void init_signals();
extern void  psignals();
extern void lsystem();
extern void help();
extern void open_getc();
extern int getc();
extern void commands();

#endif /* FUNCS_H */
