PLATFORM = 6809
CC = m6809-unknown-gcc
# pointer to pointer gcc compilation problems: use -O0.
CCOPTS = -O0
# These are wrappers for lwasm and lwar
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = lwlink
CFLAGS = -I../../Library/include -I../../Library/include/6809
LINKER_OPT = --format=raw -L../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc
LINKER_OPT += --script=../util/$(TARGET).link
ASM_OPT = -o
CRT0 = ../../Library/libs/crt0_6809.o


SRC = main.c option.c prim.c ch.c position.c input.c output.c screen.c \
    prompt.c line.c signal.c help.c ttyin.c command.c version.c


OBJ = $(SRC:.c=.o)

.SUFFIXES: .c .o

all: less

.c.o:
	$(CC) $(CFLAGS) $(CCOPTS) -c $<

less: $(OBJ) $(CRT0)
	$(LINKER) -o $@ $(LINKER_OPT) $^

clean:
	rm -f less *.rel *.asm *.lst core *.sym *.map *.noi *.lk *.ihx *.tmp *.bin *.o
