/**
 * Tool to create initial key map for ASCII keyboards (apple II)
 * 
 * Author: Thomas Cherryhomes <thom.cherryhomes@gmail.com>
 *
 */

#include <stdio.h>
#include <stdlib.h>

void main(void)
{
  unsigned int i=0;
  printf("/**\n");
  printf(" *\n");
  printf(" * KEY_H generated by mk_ascii_key_h.c\n");
  printf(" */\n");
  printf("\n\n");

  printf("unsigned char key_to_pkey[]={\n");

  for (i=0;i<133;++i)
    {
      printf("    PKEY_NOKEY, /* %03d */\n",i);
    }

  printf("};\n\n");

  /* printf("unsigned char esc_key_to_pkey[]={\n"); */

  /* for (i=0;i<128;++i) */
  /*   { */
  /*     printf("    PKEY_NOKEY, /\* 0x%02x *\/\n",i);       */
  /*   } */
  
  /* printf("};\n"); */
  
}
