PLATFORM = 8080
CC = ack
ASM = ack
AR = aal
LINKER = ack
LIBPATH=../../../Library/libs
LIBC=$(LIBPATH)/libc8080.a -lem.a
CFLAGS = -I../../../Library/include -I../../../Library/include/8080
ASM_OPT = -c -o
CRT0 = $(LIBPATH)/crt0_8080.o
CRT0NS = $(LIBPATH)/crt0nostdio_8080.o

.SUFFIXES: .c .o

SRCS = bitmap.c blockio.c cclose.c ccreat.c cfillbuf.c cflsbuf.c cmdhdl.c \
      copen.c copy.c cpm.c delete.c dirhdl.c extent.c ffc.c gensktab.c \
      hexdmp.c interact.c physio.c pip.c rename.c

OBJS = $(SRCS:.c=.o)

all: cpmfs size.report

cpmfs: $(OBJS)
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) cpmfs $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *.o

rmbak:
	rm -f *~ core
