APPOTHER =
include Makefile.common

size.report: $(APPS) $(APPSNS) $(APPTC)
	ls -l $^ > $@

clean:
	rm -f *.o $(APPS) $(APPSNS) $(APPTC) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
