include $(FUZIX_ROOT)/Applications/rules.8080

SRCSNS = \
	basename.c \
	cat.c \
	chgrp.c \
	chmod.c \
	chown.c \
	cmp.c \
	date.c \
	dirname.c \
	false.c \
	groups.c \
	head.c \
	init.c \
	kill.c \
	killall.c \
	logname.c \
	mkdir.c \
	mkfifo.c \
	mknod.c \
	pagesize.c \
	printenv.c \
	prtroot.c \
	pwd.c \
	reboot.c \
	rm.c \
	rmdir.c \
	substroot.c \
	sum.c \
	sync.c \
	tee.c \
	telinit.c \
	touch.c \
	tr.c \
	true.c \
	while1.c \
	whoami.c \
	yes.c


SRCS  = \
	banner.c \
	bd.c \
	cal.c \
	chmem.c \
	cksum.c \
	cp.c \
	cut.c \
	dd.c \
	decomp16.c \
	df.c \
	dosread.c \
	du.c \
	echo.c \
	ed.c \
	env.c \
	factor.c \
	fdisk.c \
	fgrep.c \
	free.c \
	fsck.c \
	fsck-fuzix.c \
	gptparse.c \
	grep.c \
	id.c \
	kbdrate.c \
	labelfs.c \
	ll.c \
	ls.c \
	man.c \
	manscan.c \
	mkfs.c \
	mode.c \
	more.c \
	mount.c \
	nvtool.c \
	od.c \
	passwd.c \
	ps.c \
	remount.c \
	sed.c \
	seq.c \
	setboot.c \
	setdate.c \
	size.c \
	sleep.c \
	ssh.c \
	socktest.c \
	sort.c \
	stty.c \
	su.c \
	swapon.c \
	tar.c \
	tail.c \
	termcap.c \
	umount.c \
	uname.c \
	uniq.c \
	uptime.c \
	uud.c \
	uue.c \
	wc.c \
	which.c \
	who.c \
	write.c \
	xargs.c

SRCTC = tget.c \
        tchelp.c \
	vile.c \
	marksman.c

SRCOTHER = cpuinfo.c cpuinfo-8080.s

SKIPPED =


OBJS = $(SRCS:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)
OBJTC = $(SRCTC:.c=.o)
OBJCURSES = $(SRCCURSES:.c=.o)
OBJOTHER = $(SRCOTHER:.c=.o)

APPS = $(OBJS:.o=)
APPSNS = $(OBJSNS:.o=)
APPTC = $(OBJTC:.o=)
APPCURSES = $(OBJCURSES:.o=)

all: cpuinfo $(APPS) $(APPSNS) $(APPTC) $(APPCURSES) size.report

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

$(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) $^ $(LIBC)

$(APPTC): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBPATH)/termcap8080.lib $(LIBC)

$(APPCURSES): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBPATH)/curses8080.lib $(LIBPATH)/termcap8080.lib $(LIBC)

cpuinfo-8080.o: cpuinfo-8080.s
	$(ASM) $^

cpuinfo: cpuinfo.o cpuinfo-8080.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LIBC)

size.report: $(APPS) $(APPSNS) $(APPTC)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(OBJSNS) $(APPS) $(APPSNS) $(APPTC) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin *.o size.report

rmbak:
	rm -f *~ core
