CC = m6809-unknown-gcc
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = m6809-unknown-ld
CFLAGS = -Os -I../../Library/include -I../../Library/include/6502
LDFLAGS = -L../../Library/libs -lc6809
PLATFORM = 6809

ASM_OPT = -o
LINKER_OPT = --nostdlib --no-std-crt0 --script=$(TARGET).link

.SUFFIXES: .c .o


SRCS  = banner.c \
	basename.c \
	bd.c \
	cal.c \
	cat.c \
	chgrp.c \
	chmod.c \
	chown.c \
	cksum.c \
	cmp.c \
	cp.c \
	cut.c \
	date.c \
	dd.c \
	decomp16.c \
	df.c \
	dirname.c \
	dosread.c \
	du.c \
	echo.c \
	ed.c \
	factor.c \
	false.c \
	fdisk.c \
	fgrep.c \
	fsck.c \
	grep.c \
	head.c \
	id.c \
	init.c \
	kill.c \
	ll.c \
	ln.c \
	logname.c \
	ls.c \
	man.c \
	mkdir.c \
	mkfs.c \
	mkfifo.c \
	mknod.c \
	more.c \
	mount.c \
	mv.c \
	od.c \
	pagesize.c \
	passwd.c \
	patchcpm.c \
	printenv.c \
	prtroot.c \
	ps.c \
	pwd.c \
	rm.c \
	rmdir.c \
	sed.c \
	sleep.c \
	ssh.c \
	sort.c \
	stty.c \
	sum.c \
	su.c \
	sync.c \
	tee.c \
	tail.c \
	touch.c \
	tr.c \
	true.c \
	umount.c \
	uniq.c \
	uud.c \
	uue.c \
	wc.c \
	which.c \
	who.c \
	whoami.c \
	write.c \
	xargs.c \
	yes.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS)

$(OBJS): $(SRCS)

#.c.o:
#	$(CC) -c $<

%: %.o
	$(LINKER) -o $@ $(LDFLAGS) $<

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin

rmbak:
	rm -f *~ core
