PLATFORM = 6809
CC = m6809-unknown-gcc
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = m6809-unknown-ld
CFLAGS = -I../../Library/include -I../../Library/include/6809
LINKER_OPT = --oformat=raw -L../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc
LINKER_OPT += --script=$(TARGET).link
ASM_OPT = -o
CRT0 = ../../Library/libs/crt0_6809.o
CRT0NS = ../../Library/libs/crt0nostdio_6809.o

.SUFFIXES: .c .o

SRCSNS = \
	basename.c \
	cat.c \
	chgrp.c \
	chmod.c \
	chown.c \
	cmp.c \
	date.c \
	dirname.c \
	false.c \
	groups.c \
	head.c \
	init.c \
	kill.c \
	killall.c \
	logname.c \
	mkdir.c \
	mkfifo.c \
	mknod.c \
	pagesize.c \
	printenv.c \
	prtroot.c \
	pwd.c \
	reboot.c \
	rm.c \
	rmdir.c \
	substroot.c \
	sum.c \
	sync.c \
	tee.c \
	telinit.c \
	touch.c \
	tr.c \
	true.c \
	while1.c \
	whoami.c \
	yes.c


SRCS  = \
	banner.c \
	bd.c \
	bogomips.c \
	cal.c \
	chmem.c \
	cksum.c \
	cp.c \
	cut.c \
	dd.c \
	decomp16.c \
	df.c \
	dosread.c \
	du.c \
	echo.c \
	ed.c \
	env.c \
	factor.c \
	fdisk.c \
	fforth.c \
	fgrep.c \
	free.c \
	fsck.c \
	fsck-fuzix.c \
	gptparse.c \
	grep.c \
	id.c \
	kbdrate.c \
	labelfs.c \
	ll.c \
	ls.c \
	man.c \
	manscan.c \
	mkfs.c \
	mode.c \
	more.c \
	mount.c \
	nvtool.c \
	od.c \
	passwd.c \
	ps.c \
	remount.c \
	sed.c \
	seq.c \
	setboot.c \
	setdate.c \
	size.c \
	sleep.c \
	ssh.c \
	socktest.c \
	sort.c \
	stty.c \
	su.c \
	swapon.c \
	tar.c \
	tail.c \
	termcap.c \
	umount.c \
	uname.c \
	uniq.c \
	uptime.c \
	uud.c \
	uue.c \
	wc.c \
	which.c \
	who.c \
	write.c \
	xargs.c

SRCTC = tget.c \
        tchelp.c \
	marksman.c \
	vile.c \


SKIPPED =


OBJS = $(SRCS:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)
OBJTC = $(SRCTC:.c=.o)
OBJCURSES = $(SRCCURSES:.c=.o)

APPS = $(OBJS:.o=)
APPSNS = $(OBJSNS:.o=)
APPTC = $(OBJTC:.o=)
APPCURSES = $(OBJCURSES:.o=)

all: $(APPS) $(APPSNS) $(APPTC) $(APPCURSES) size.report

$(APPS): $(CRT0)
$(APPSNS): $(CRT0NS)

$(APPS) $(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $^

$(APPTC): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) -ltermcap6809 $^

$(APPCURSES): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) -lcurses6809 -ltermcap6809 $^

size.report: $(APPS) $(APPSNS) $(APPTC)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(OBJSNS) $(APPS) $(APPSNS) $(APPTC) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin *.o size.report

rmbak:
	rm -f *~ core
