PLATFORM = 6809
CC = m6809-unknown-gcc
# These are wrappers for lwasm and lwar
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = lwlink
CFLAGS = -I../../Library/include -I../../Library/include/6502
LINKER_OPT = --format=raw -L../../Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc
LINKER_OPT += --script=$(TARGET).link
ASM_OPT = -o
CRT0 = ../../Library/libs/crt0_6809.o

.SUFFIXES: .c .o


SRCS  = banner.c \
	basename.c \
	bd.c \
	cal.c \
	cat.c \
	chgrp.c \
	chmod.c \
	chown.c \
	cksum.c \
	cmp.c \
	cp.c \
	cut.c \
	date.c \
	dd.c \
	decomp16.c \
	df.c \
	dirname.c \
	dosread.c \
	du.c \
	echo.c \
	ed.c \
	env.c \
	factor.c \
	false.c \
	fdisk.c \
	fgrep.c \
	fsck.c \
	grep.c \
	head.c \
	id.c \
	init.c \
	kill.c \
	ll.c \
	ln.c \
	logname.c \
	ls.c \
	man.c \
	mkdir.c \
	mkfs.c \
	mkfifo.c \
	mknod.c \
	more.c \
	mount.c \
	mv.c \
	od.c \
	pagesize.c \
	passwd.c \
	patchcpm.c \
	printenv.c \
	prtroot.c \
	ps.c \
	pwd.c \
	reboot.c \
	rm.c \
	rmdir.c \
	sed.c \
	sleep.c \
	ssh.c \
	sort.c \
	stty.c \
	sum.c \
	su.c \
	sync.c \
	tee.c \
	tail.c \
	telinit.c \
	touch.c \
	tr.c \
	true.c \
	umount.c \
	uniq.c \
	uptime.c \
	uud.c \
	uue.c \
	wc.c \
	which.c \
	who.c \
	whoami.c \
	write.c \
	xargs.c \
	yes.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) sizes

$(OBJS): $(SRCS)

$(APPS): $(CRT0)

%: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $<

sizes: $(APPS)
	ls -l $(APPS) > size.report

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
