PLATFORM = 68000
CC = m68k-uclinux-gcc
ASM = m68k-uclinux-as
AR = m68k-uclinux-ar
LINKER = m68k-uclinux-ld
CFLAGS = -fno-strict-aliasing -fomit-frame-pointer -fno-builtin -msoft-float -Wall -m68000 -Os -I../../Library/include -I../../Library/include/68000
LINKER_OPT = -L../../Library/libs -lc68000
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += --emit-relocs -L$(LIBGCCDIR) -lgcc -T ../../Library/elf2flt.ld
CRT0 = ../../Library/libs/crt0_68000.o
CRT0NS = ../../Library/libs/crt0nostdio_68000.o
# For now while we get going. Really we want to use some kind of elf2zmagic
# with relocs.
ELF2FUZIX = elf2flt -s 16384
.SUFFIXES: .c .o

SRCSNS = \
	basename.c \
	cat.c \
	chgrp.c \
	chmod.c \
	chown.c \
	cmp.c \
	date.c \
	dirname.c \
	false.c \
	groups.c \
	head.c \
	init.c \
	kill.c \
	killall.c \
	logname.c \
	mkdir.c \
	mkfifo.c \
	mknod.c \
	pagesize.c \
	printenv.c \
	prtroot.c \
	pwd.c \
	reboot.c \
	rm.c \
	rmdir.c \
	substroot.c \
	sum.c \
	sync.c \
	tee.c \
	telinit.c \
	touch.c \
	tr.c \
	true.c \
	while1.c \
	whoami.c \
	yes.c


SRCS  = \
	banner.c \
	bd.c \
	cal.c \
	chmem.c \
	cksum.c \
	cp.c \
	cut.c \
	dd.c \
	decomp16.c \
	df.c \
	dosread.c \
	du.c \
	echo.c \
	ed.c \
	env.c \
	factor.c \
	fdisk.c \
	fforth.c \
	fgrep.c \
	free.c \
	fsck.c \
	fsck-fuzix.c \
	gptparse.c \
	grep.c \
	id.c \
	kbdrate.c \
	labelfs.c \
	ll.c \
	ls.c \
	man.c \
	manscan.c \
	mkfs.c \
	mode.c \
	more.c \
	mount.c \
	nvtool.c \
	od.c \
	passwd.c \
	ps.c \
	remount.c \
	sed.c \
	seq.c \
	setboot.c \
	setdate.c \
	size.c \
	sleep.c \
	ssh.c \
	socktest.c \
	sort.c \
	stty.c \
	su.c \
	swapon.c \
	tar.c \
	tail.c \
	termcap.c \
	umount.c \
	uname.c \
	uniq.c \
	uptime.c \
	uud.c \
	uue.c \
	wc.c \
	which.c \
	who.c \
	write.c \
	xargs.c

SRCTC = tget.c \
        tchelp.c \
	vile.c \
	marksman.c

SKIPPED =


OBJS = $(SRCS:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)
OBJTC = $(SRCTC:.c=.o)
OBJCURSES = $(SRCCURSES:.c=.o)

APPS = $(OBJS:.o=)
APPSNS = $(OBJSNS:.o=)
APPTC = $(OBJTC:.o=)
APPCURSES = $(OBJCURSES:.o=)

all: $(APPS) $(APPSNS) $(APPTC) $(APPCURSES) size.report

$(APPS): $(CRT0)
$(APPSNS): $(CRT0NS)
$(APPTC): $(CRT0)
$(APPCURSES): $(CRT0)

$(APPS) $(APPSNS): %: %.o
	$(LINKER) $^ -o $@.bin $(LINKER_OPT)
	$(ELF2FUZIX) -o $@ $@.bin

$(APPTC): %: %.o
	$(LINKER) $^ -o $@.bin -ltermcap68000 $(LINKER_OPT)
	$(ELF2FUZIX) -o $@ $@.bin

$(APPCURSES): %: %.o
	$(LINKER) $^ -o $@.bin -lcurses68000 -ltermcap68000 $(LINKER_OPT)
	$(ELF2FUZIX) -o $@ $@.bin

size.report: $(APPS) $(APPSNS) $(APPTC)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(OBJSNS) $(OBJTC) $(OBJCURSES)
	rm -f $(APPS) $(APPSNS) $(APPTC) $(APPCURSES)
	rm -f $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report *.o

rmbak:
	rm -f *~ core
