PLATFORM = 6502
CC = cl65
AS = ca65
LINKER = cl65
CFLAGS = -t none -O -D__STDC__ -c -O -I../../Library/include -I../../Library/include/6502
LINKER_OPT = -L../../Library/libs -C ../../Library/libs/ld65-$(TARGET).cfg
AS_OPT = -o
CRT0 = ../../Library/libs/crt0_6502.o
CRT0NS = ../../Library/libs/crt0nostdio_6502.o

.SUFFIXES: .c .o

SRCSNS = \
	basename.c \
	cat.c \
	chgrp.c \
	chmod.c \
	chown.c \
	cmp.c \
	date.c \
	dirname.c \
	false.c \
	groups.c \
	head.c \
	init.c \
	kill.c \
	killall.c \
	line.c \
	logname.c \
	mkdir.c \
	mkfifo.c \
	mknod.c \
	pagesize.c \
	printenv.c \
	prtroot.c \
	pwd.c \
	reboot.c \
	rm.c \
	rmdir.c \
	substroot.c \
	sum.c \
	sync.c \
	tee.c \
	telinit.c \
	touch.c \
	tr.c \
	true.c \
	while1.c \
	whoami.c \
	yes.c

SRCS  = banner.c \
	bd.c \
	cal.c \
	chmem.c \
	cksum.c \
	cp.c \
	cut.c \
	dd.c \
	df.c \
	dosread.c \
	du.c \
	echo.c \
	ed.c \
	env.c \
	factor.c \
	fdisk.c \
	fgrep.c \
	free.c \
	fsck.c \
	fsck-fuzix.c \
	grep.c \
	id.c \
	kbdrate.c \
	labelfs.c \
	ll.c \
	ls.c \
	man.c \
	manscan.c \
	mkfs.c \
	mode.c \
	more.c \
	mount.c \
	nvtool.c \
	od.c \
	passwd.c \
	ps.c \
	remount.c \
	seq.c \
	setboot.c \
	setdate.c \
	size.c \
	sleep.c \
	ssh.c \
	sort.c \
	stty.c \
	su.c \
	swapon.c \
	tail.c \
	tar.c \
	termcap.c \
	umount.c \
	uname.c \
	uniq.c \
	uptime.c \
	uud.c \
	uue.c \
	wc.c \
	which.c \
	who.c \
	write.c \
	xargs.c

SRCTC = tget.c \
        tchelp.c \
	marksman.c

SRCOTHER = cpuinfo.c \
	   cpuinfo-6502.s

SKIPPED = decomp16.c sed.c


OBJS = $(SRCS:.c=.o)
OBJSNS = $(SRCSNS:.c=.o)
OBJTC = $(SRCTC:.c=.o)
OBJOTHER = $(SRCOTHER:.c=.o)

APPS = $(OBJS:.o=)
APPSNS = $(OBJSNS:.o=)
APPTC = $(OBJTC:.o=)

all: cpuinfo $(APPS) $(APPSNS) $(APPTC) size.report

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ c6502.lib -m $@.map

$(APPSNS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0NS) $^ c6502.lib -m $@.map

$(APPTC): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ termcap6502.lib c6502.lib

cpuinfo: cpuinfo.o cpuinfo-6502.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ c6502.lib -m $@.map

size.report: $(APPS) $(APPSNS) $(APPTC)
	ls -l $^ > $@

clean:
	rm -f *.o $(APPS) $(APPSNS) $(APPTC) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core
